FROM apache/airflow:2.7.1

# Switch to airflow user first
USER airflow

# Install required Python packages
RUN pip install --no-cache-dir pymysql dbt-core dbt-mysql pandas sqlalchemy

# Set Airflow environment variables
ENV AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=mysql+pymysql://root:root@mysql:3306/playstore
ENV AIRFLOW__CORE__EXECUTOR=LocalExecutor

EXPOSE 8080

# Run Airflow scheduler + webserver at runtime
CMD ["bash", "-c", "airflow db init && airflow scheduler & airflow webserver"]
