version: "3.8"

services:
  # ==========================================
  # MySQL Database
  # ==========================================
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: playstore
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./ingestion/mysql_ingestion/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - data_pipeline_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # ==========================================
  # Airflow - WORKING VERSION
  # ==========================================
  airflow:
    image: apache/airflow:2.7.1-python3.10
    container_name: airflow
    user: "50000:0"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: mysql+pymysql://root:root@mysql:3306/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      DBT_PROFILES_DIR: /app/dbt_project
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/app/data
      - ./dbt_project:/app/dbt_project
      - airflow_data:/opt/airflow
      - airflow_logs:/opt/airflow/logs
    ports:
      - "8080:8080"
    networks:
      - data_pipeline_network
    restart: unless-stopped
    entrypoint: /bin/bash
    command:
      - -c
      - |
        set -e
        
        echo "======================================"
        echo "  Installing Python packages..."
        echo "======================================"
        
        # Upgrade pip first
        pip install --no-cache-dir --upgrade pip -q
        
        # Install packages with correct versions for Python 3.10
        pip install --no-cache-dir -q \
          pymysql==1.1.0 \
          cryptography==41.0.5 \
          pandas==2.0.3 \
          numpy==1.24.3 \
          dbt-core==1.7.0 \
          dbt-mysql==1.7.0
        
        echo "✓ All packages installed successfully"
        
        echo "======================================"
        echo "  Initializing Airflow database..."
        echo "======================================"
        
        airflow db init
        
        echo "✓ Airflow database initialized"
        
        echo "======================================"
        echo "  Creating admin user..."
        echo "======================================"
        
        airflow users create \
          --username admin \
          --password admin \
          --firstname Admin \
          --lastname User \
          --role Admin \
          --email admin@example.com 2>/dev/null || echo "User already exists"
        
        echo "✓ Admin user ready"
        
        echo "======================================"
        echo "  Starting Airflow services..."
        echo "======================================"
        echo ""
        echo "  Airflow UI will be available at:"
        echo "  http://localhost:8080"
        echo ""
        echo "  Login credentials:"
        echo "  Username: admin"
        echo "  Password: admin"
        echo ""
        echo "======================================"
        
        # Start scheduler in background
        airflow scheduler &
        
        # Start webserver (foreground)
        exec airflow webserver

  # ==========================================
  # MongoDB
  # ==========================================
  mongo_db:
    image: mongo:6.0
    container_name: mongo_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - data_pipeline_network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # ==========================================
  # Data Ingestion
  # ==========================================
  ingestion:
    image: python:3.10-slim
    container_name: ingestion_app
    working_dir: /app 
    depends_on:
      mysql:
        condition: service_healthy
      mongo_db:
        condition: service_healthy
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: playstore
      MONGO_HOST: mongo_db
      MONGO_PORT: 27017
    volumes:
      - .:/app
    networks:
      - data_pipeline_network
    command:
      - /bin/bash
      - -c
      - |
        echo "Installing system dependencies..."
        apt-get update -qq 
        apt-get install -y -qq default-libmysqlclient-dev build-essential
        
        echo "Installing Python packages..."
        pip install --no-cache-dir -q pymysql pandas pymongo sqlalchemy
        
        echo "Running ingestion script..."
        python ingestion/data_integration/integration_script.py
        
        echo "✓ Ingestion completed successfully"
    restart: on-failure

volumes:
  mysql_data:
  mongo_data:
  airflow_data:
  airflow_logs:

networks:
  data_pipeline_network:
    driver: bridge