version: 2

models:
  - name: stg_apps
    description: "Staging table for apps"
    columns:
      - name: App
        description: "App name"
      - name: Category
        description: "App category"
      - name: Type
        description: "Free or Paid"
      - name: Price
        description: "Price if paid"

  - name: stg_reviews
    description: "Staging table for reviews"
    columns:
      - name: review_id
        description: "Review ID"
      - name: app_id
        description: "App ID"
      - name: sentiment
        description: "Sentiment score"
