name: 'apppulse'
version: '1.0.0'
config-version: 2

profile: 'apppulse'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  apppulse:
    marts:
      +materialized: table
    staging:
      +materialized: view